
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 10;
  public static final int LT = 12;
  public static final int OVER = 11;
  public static final int ELSE = 2;
  public static final int NOTEQ = 17;
  public static final int PLUS = 8;
  public static final int RPAREN = 22;
  public static final int INT = 4;
  public static final int SEMI = 19;
  public static final int WHILE = 7;
  public static final int LCURLYB = 25;
  public static final int RETURN = 5;
  public static final int ERROR = 29;
  public static final int IF = 3;
  public static final int LPAREN = 21;
  public static final int GT = 14;
  public static final int ID = 27;
  public static final int NUM = 28;
  public static final int COMMA = 20;
  public static final int LTEQ = 13;
  public static final int EOF = 0;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int EQ = 16;
  public static final int GTEQ = 15;
  public static final int RCURLYB = 26;
  public static final int VOID = 6;
  public static final int LSQUAREB = 23;
  public static final int RSQUAREB = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LT",
  "LTEQ",
  "GT",
  "GTEQ",
  "EQ",
  "NOTEQ",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQUAREB",
  "RSQUAREB",
  "LCURLYB",
  "RCURLYB",
  "ID",
  "NUM",
  "ERROR"
  };
}

