
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int LT = 4;
  public static final int OVER = 9;
  public static final int ELSE = 16;
  public static final int PLUS = 6;
  public static final int INT = 18;
  public static final int RPAREN = 11;
  public static final int WHILE = 21;
  public static final int SEMI = 12;
  public static final int RETURN = 19;
  public static final int ERROR = 15;
  public static final int IF = 17;
  public static final int LPAREN = 10;
  public static final int GT = 5;
  public static final int ID = 13;
  public static final int NUM = 14;
  public static final int EOF = 0;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int EQ = 3;
  public static final int VOID = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "ID",
  "NUM",
  "ERROR",
  "ELSE",
  "IF",
  "INT",
  "RETURN",
  "VOID",
  "WHILE"
  };
}

